[package]
name = "libfsntfs-sys"
description = "Rust bindings for libfsntfs (https://github.com/libyal/libfsntfs)"
homepage = "https://github.com/omerbenamram/libfsntfs-sys"
repository = "https://github.com/omerbenamram/libfsntfs-sys"
license = "LGPL-3.0+"

readme = "README.md"
version = "0.1.3"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"
links = "libfsntfs"

[build-dependencies]
failure = "0.1.5"
libyal-rs-common-build = {path = "../common-build"}

[features]

default = []

# Use when building dynamic bindings.
dynamic_link = []